name: arx-py312
channels:
  - robostack-jazzy
  - conda-forge
dependencies:
  - python=3.12
  - cxx-compiler
  - cmake
  - ros-jazzy-kdl-parser
  - ninja
  - orocos-kdl
  - eigen
  - boost
  - spdlog
  - pybind11
  - numpy
  - click
  - pyzmq
  - pynput
  - pip
  - conda-forge::soem=1.4.0 # This package is missing in aarch64
  # To install it on aarch64 (arm64), comment out this package and first create the arx-py312 environment.
  # Directly clone the SOEM repository and install it to the conda environment (ensure $CONDA_PREFIX points to arx-py312):
  # `conda activate arx-py312`
  # `git clone https://github.com/OpenEtherCATsociety/SOEM.git && cd SOEM`
  # `mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX .. && make -j && make install`
  - pip:
      - atomics
      - spnav @ https://github.com/cheng-chi/spnav/archive/c1c938ebe3cc542db4685e0d13850ff1abfdb943.tar.gz
